export const blogList = [{
        id: 1,
        title: 'What is NPM ?',
        category: 'NPM',
        subCategory: ['frontend', 'React', 'NPM'],
        description: "NPM  works as a manage package but does not stand Node Package Manager. NPM does not have a Long Form. NPM is a standard repository all the packages are hoisting their, packages like their libraries, utilities comes from npm and npm package manage their. It will manage the packages and install in your System.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'Sep 10, 2023',
        cover: '/assets/images/github-npm-blog.webp',
    },
    // {
    //     id: 2,
    //     title: 'What is REDUX and REDUX - TOOLKIT',
    //     category: 'REDUX',
    //     subCategory: ['vacation', 'holidays', 'sight seeing'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     authorName: 'Tejas Banait',
    //     authorAvatar: '/assets/images/author.jpg',
    //     createdAt: 'Sep 12, 2023',
    //     cover: '/assets/images/redux-blog.png',
    // },
    {
        id: 3,
        title: 'What Is PARCEL',
        category: 'PARCEL',
        subCategory: ['Parcel', 'WebPack', 'Bundles'],
        description: "Parcel are Created Server giving 1234 server. Parcel are project own dependencies this is known as Transitive Dependencies. Parcel Doing It for You : Dev Build, Local Server, HML (Hot module Replacement, Image optimization, Minification, Bundling, Compress ",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/react-parcel.png',
    },
    // {
    //     id: 4,
    //     title: 'What is JSX?',
    //     category: 'JSX',
    //     subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     authorName: 'Tejas Banait',
    //     authorAvatar: '/assets/images/author.jpg',
    //     createdAt: 'June 03, 2021',
    //     cover: '/assets/images/react-jsx.jpeg',
    // },
    // {
    //     id: 5,
    //     title: 'Loaded BBQ Baked Potatoes',
    //     category: 'REACT ROUTER',
    //     subCategory: ['bbq', 'food', 'lifestyle'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     authorName: 'Tejas Banait',
    //     authorAvatar: '/assets/images/author.jpg',
    //     createdAt: 'June 03, 2021',
    //     cover: '/assets/images/react-router.webp',
    // },
    // {
    //     id: 6,
    //     title: 'Difference Between Package.json and Package-lock.json',
    //     category: 'REACT PACKAGES',
    //     subCategory: ['beaches', 'sea', 'holidays'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     authorName: 'Tejas Banait',
    //     authorAvatar: '/assets/images/author.jpg',
    //     createdAt: 'June 03, 2021',
    //     cover: '/assets/images/react-package.png',
    // },
    // {
    //     id: 7,
    //     title: 'Art & Perception',
    //     category: 'REACT COMPONENETS',
    //     subCategory: ['skill', 'design', 'passion'],
    //     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    //     authorName: 'Tejas Banait',
    //     authorAvatar: '/assets/images/author.jpg',
    //     createdAt: 'June 03, 2021',
    //     cover: '/assets/images/React-components.png',
    // },
];