export const blogList = [{
        id: 1,
        title: '7 CSS tools you should be using ',
        category: 'NPM',
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/github-npm-blog.webp',
    },
    {
        id: 2,
        title: 'Milan Places That Highlight The City',
        category: 'REDUX',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/redux-blog.png',
    },
    {
        id: 3,
        title: 'Online Shopping – An Alternative to Shopping in the Mall',
        category: 'PARCEL',
        subCategory: ['e-commerce store', 'clothing', 'shopping store'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/react-parcel.png',
    },
    {
        id: 4,
        title: 'ADVENTURE IN YOU',
        category: 'JSX',
        subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/react-jsx.jpeg',
    },
    {
        id: 5,
        title: 'Loaded BBQ Baked Potatoes',
        category: 'REACT ROUTER',
        subCategory: ['bbq', 'food', 'lifestyle'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/react-router.webp',
    },
    {
        id: 6,
        title: 'Difference Between Package.json and Package-lock.json',
        category: 'REACT PACKAGES',
        subCategory: ['beaches', 'sea', 'holidays'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/react-package.png',
    },
    {
        id: 7,
        title: 'Art & Perception',
        category: 'REACT COMPONENETS',
        subCategory: ['skill', 'design', 'passion'],
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Tejas Banait',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/React-components.png',
    },
];